version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: install_dep.sh
      timeout: 3000
  AfterInstall:
    - location: after_install.sh
      timeout: 3000