version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
hooks:
  BeforeInstall:
   - location: install_dep.sh
     timeout: 300
  ApplicationStart:
   - location: updateSS.sh
     timeout: 60000